services:
  - type: web
    name: smarturl-telegram-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: PORT
        value: 8080
    healthCheckPath: /
    healthCheckTimeout: 5s
    autoDeploy: true
    numInstances: 1
    plan: free 
